apiVersion: v1
kind: Pod
metadata:
  name: spring-hello
  namespace: default
  labels:
    name: spring-hello
spec:
  containers:
    - image: nhan99dn/spring-hello:latest
      name: spring-hello
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
